### ISSUE TITLE
能给个数据库么？

### ISSUE THREAD

**Issue by aen516954023** [skyselang/yylAdmin#1]
登陆提示数据库错误 能给个数据库么？

**Comment by skyselang** [comment]
https://github.com/skyselang/yyl-admin-php/blob/master/public/storage/database/yyladmin.sql

**Comment by skyselang** [comment]
数据库在public/storage/adminsql文件夹

**Comment by liyujiang-gzu** [comment]
> 数据库在public/storage/adminsql文件夹

最新代码不存在`public/storage/adminsql`，是 [public/private/yyladmin.sql](https://github.com/skyselang/yylAdmin/blob/master/public/private/yyladmin.sql) 吧？

**Comment by skyselang** [comment]
数据库文件：public/private/yyladmin.sql
