### ISSUE TITLE
缓存驱动使用 `file` 时在Windows系统下出错

### ISSUE THREAD

**Issue by liyujiang-gzu** [skyselang/yylAdmin#2]
`'prefix'     => 'yyl:'`中的“:”是特殊符号，导致无法创建目录

**Comment by skyselang** [comment]
请使用Redis，速度更快

**Comment by liyujiang-gzu** [comment]
> 请使用Redis，速度更快

额，服务器不支持redis

**Comment by liyujiang-gzu** [comment]
See [commit#724c54b413db51e0f102693af25894d6583d6652](https://github.com/skyselang/yylAdmin/commit/724c54b413db51e0f102693af25894d6583d6652)
