### ISSUE TITLE
后端代码就没有

### ISSUE THREAD

**Issue by gyp666** [skyselang/yylAdmin#5]
第一次下载断开被删了，第二次下载只有git隐藏文件！
安装完tp6该干什么了？ 我这composer install报错Composer could not find the config file: D:\composer
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section！！！！ 要怎么解决

**Comment by skyselang** [comment]
重新拉取，国内访问github网速慢，可以访问码云
